### ISSUE TITLE
Get Problem With Windows7 VS2017 when running

### ISSUE THREAD

**Issue by mindoff6502** [wjakob/nori#10]
Successfully compile nori.exe
put it to nori\scenes\pa1 folder
run command below:
nori bunny.xml

get error
Fatal error: Error while parsing "bunny.xml": A constructor for class "normals" could not be found!
(at line 8, col 13)

Try other xxx.xml,same error.

All Compile return success, no fail was seen.
What should I do?

**Comment by merlinND** [comment]
Hello @mindoff6502,

The code provided in this repository is only a template, designed to be completed by students following the 5 assignments on this website: https://wjakob.github.io/nori/
The Normals integrator (`normals.cpp`) is created in the first assignment, the scene you've tried should work after you've completed it :)
