### ISSUE TITLE
has_trivial_copy_constructor is not a member of ‘std’

### ISSUE THREAD

**Issue by andyyankai** [wjakob/nori#14]
I tried to makefile for both cmake ver=3.11.4 and 3.12 but receive the same issue nori/ext/tbb/include/tbb/pipeline.h:328:74: error: ‘has_trivial_copy_constructor’ is not a member of ‘std’

**Comment by andyyankai** [comment]
I solve this issue by change it into is_trivially_copy_constructible in pipeline.h of tdd. I submited my pull request can see if this should be an issue.

**Comment by kevenv** [comment]
Thanks @andyyankai 
same issue on clang 5.0.1 and gcc 7.3.1
