### ISSUE TITLE
Issue in generating CMake files with macOS 10.14.3

### ISSUE THREAD

**Issue by harrytodorov** [wjakob/nori#16]
On macOS 10.14.3 (Mojave) CMake could not find `pthread.h`:
```
-- Looking for pthread.h - not found
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindThreads.cmake:191 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  ext/nanogui/ext/glfw/CMakeLists.txt:60 (find_package)
```

It is due to the directory, where `pthread.h` is located on newer versions on MacOs (starting from Mojave). A fix that worked for me is:
```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

[source](https://github.com/neovim/neovim/issues/9050#issuecomment-424417456)

**Comment by Aaron19960821** [comment]
I tried running this .pkg file but it is not working. Did you also do something else to fix this issue?

**Comment by harrytodorov** [comment]
No, back then only installing the `*.pkg` file worked for me. But currently, on Catalina (10.15.1), I'm experiencing a similar issue, which I haven't solved yet. [Here](https://stackoverflow.com/questions/58524715/failing-to-compile-a-c-application-under-macos-catalina-10-15) is the StackOverflow post about it, where people have come up with some suggestions, which can be helpful to you.

**Comment by Aaron19960821** [comment]
> No, back then only installing the `*.pkg` file worked for me. But currently, on Catalina (10.15.1), I'm experiencing a similar issue, which I haven't solved yet. [Here](https://stackoverflow.com/questions/58524715/failing-to-compile-a-c-application-under-macos-catalina-10-15) is the StackOverflow post about it, where people have come up with some suggestions, which can be helpful to you.

Thank you for your kind reply. I found that this error happens because I upgrade my xcode to MacOS 10.15 SDK. Maybe redirect xcode to a different version (use xcode-select -s [path]) will help.

**Comment by harrytodorov** [comment]
> > No, back then only installing the `*.pkg` file worked for me. But currently, on Catalina (10.15.1), I'm experiencing a similar issue, which I haven't solved yet. [Here](https://stackoverflow.com/questions/58524715/failing-to-compile-a-c-application-under-macos-catalina-10-15) is the StackOverflow post about it, where people have come up with some suggestions, which can be helpful to you.
> 
> Thank you for your kind reply. I found that this error happens because I upgrade my xcode to MacOS 10.15 SDK. Maybe redirect xcode to a different version (use xcode-select -s [path]) will help.

Oh, thank you very much! I've almost lost hope in solving the issue and was using recently another system to work on Nori, but downgrading XCode worked out fine for me! The version, which worked for me is 10.2.1 ([here](https://developer.apple.com/download/more/) is where one can download it from)

**Comment by tizian** [comment]
This turned out to be some weird change in the way the Xcode build target was set up inside of Nori's CMake file. We pushed some changes this week that should make everything compile again on the latest versions of macOS & Xcode.
