### ISSUE TITLE
nano gui segmentation fault on Ubuntu 16.06

### ISSUE THREAD

**Issue by sylqiu** [wjakob/nori#17]
I am able to build and run the nori executable, however it appears that the nano gui will return a segmentation fault once I close the window, and no .exr file is saved. I change the order of saving and nano gui in main.cpp, and it is able to save but the same segmentation fault will pop up when the window is closed. This happens on my Ubuntu 16.06 machine (with discrete GPU), but not on my Windows Machine (integrated GPU). What could potentially be the problem?

**Comment by dvicini** [comment]
I was trying to reproduce your error but I wasn't able to. I am using Kubuntu 19.10 and a discrete Nvidia GPU. I didn't get a segfault when closing the UI and the EXR and PNG were saved correctly. 

Are you sure you have the latest version of Nori and all the submodules (i.e. run `git submodule update --recursive`) ? We recently updated the versions of the submodules and also improved the CMake setup slightly. 

Other than that, I would be curious to know whether you also get a segfault when running and closing the example applications from the NanoGUI repository (https://github.com/wjakob/nanogui). This segfault sounds more like a NanoGUI issue than a Nori issue.

**Comment by sylqiu** [comment]
Thanks for the reply. However when I try to build the newest Nori (without modification) I encounter the following on my Ubuntu 16.06 machine:
```
warptest.cpp:871:32: error: converting to ‘std::tuple<WarpType, float, float>’
 from initializer list would use explicit constructor 
‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) 
[with _UElements = {WarpType&, float&, float&}; <template-parameter-2-2> = void;
 _Elements = {WarpType, float, float}]’
     return { tp, value, value2 };
```

**Comment by dvicini** [comment]
Interesting, could you try just replacing the return statement 
```
return { tp, value, value2};
```
with 
```
return std::make_tuple(tp, value, value2);
```
The issue is most likely caused by your compiler being a bit outdated. Changing the return statement should resolve the compilation error.

**Comment by sylqiu** [comment]
Thanks for the suggestion! Nori works as expected, no segmentation fault occurred.
