### ISSUE TITLE
NVIDIA GPU-based rendering

### ISSUE THREAD

**Issue by Zrrr1997** [wjakob/nori#23]
Hi,

I was wondering whether its possible to use an NVIDIA-GPU for the renderer or whether it is entirely CPU-multithreading based. 

Thanks in advance!

**Comment by merlinND** [comment]
Hello,

Nori is simplified renderer for educational use. It does not include GPU support (unlike e.g. [Mitsuba 2](https://github.com/mitsuba-renderer/mitsuba2)).
