### ISSUE TITLE
nori website can not see assignment

### ISSUE THREAD

**Issue by wlxklyh** [wjakob/nori#29]
[In nori](https://wjakob.github.io/nori/)
2023.10.18 can  see assianment.
2023.10.19 can not see assianment.
![image](https://github.com/wjakob/nori/assets/6959061/df9057fb-216c-4376-8fee-a01d4e2afd58)

**Comment by merlinND** [comment]
Hello @wlxklyh,

Per the README,

> Last year's version of Nori including a full set of assignment descriptions can be found in the following [archive](https://github.com/wjakob/nori-old).

Which is hosted at this link: https://wjakob.github.io/nori-old/

**Comment by wlxklyh** [comment]
Thank you~~ I have not paying attention to the README.
