### ISSUE TITLE
XML parsing of rotations

### ISSUE THREAD

**Issue by DrLSimon** [wjakob/nori#30]
Hi, 
This is just a minor comment w.r.t the parser of Transform, for rotation, when the axis provided in the XML is not normalized, the produced transformation is actually not a rotation. 
Is this the intended behaviour. If not I would suggest normalizing the axis in the parser, here :
[parser.cpp#L270C1-L271C1](https://github.com/wjakob/nori/blob/a13cce68124c42c326c999735e033a83c573264c/src/parser.cpp#L270C1-L271C1)

Best regards, Loic Simon

**Comment by wjakob** [comment]
Thanks for the report Loic, this is fixed now.
